# Generated by Django 5.1.3 on 2025-02-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Prod_Image',
        ),
    ]
