# Generated by Django 5.1.3 on 2025-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_remove_cartdb_prod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Prod_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart Images'),
        ),
    ]
