# Generated by Django 5.1.4 on 2025-01-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_rename_prodiuctimage_productdb_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Category_Name',
            new_name='CategoryName',
        ),
    ]
