# Generated by Django 5.1.4 on 2025-01-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_category_name_productdb_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='CategoryName',
            new_name='Category_Name',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='ProductImage',
            new_name='Product_Image',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='ProductName',
            new_name='Product_Name',
        ),
    ]
